# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sdnv/PinkRabbitMQ/linux

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sdnv/PinkRabbitMQ/linux/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sdnv/PinkRabbitMQ/linux/build/CMakeFiles /home/sdnv/PinkRabbitMQ/linux/build/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sdnv/PinkRabbitMQ/linux/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PinkRabbitMQ64

# Build rule for target.
PinkRabbitMQ64: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PinkRabbitMQ64
.PHONY : PinkRabbitMQ64

# fast build rule for target.
PinkRabbitMQ64/fast:
	$(MAKE) -f CMakeFiles/PinkRabbitMQ64.dir/build.make CMakeFiles/PinkRabbitMQ64.dir/build
.PHONY : PinkRabbitMQ64/fast

#=============================================================================
# Target rules for targets named unittest

# Build rule for target.
unittest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unittest
.PHONY : unittest

# fast build rule for target.
unittest/fast:
	$(MAKE) -f CMakeFiles/unittest.dir/build.make CMakeFiles/unittest.dir/build
.PHONY : unittest/fast

common.o: common.cpp.o

.PHONY : common.o

# target to build an object file
common.cpp.o:
	$(MAKE) -f CMakeFiles/unittest.dir/build.make CMakeFiles/unittest.dir/common.cpp.o
.PHONY : common.cpp.o

common.i: common.cpp.i

.PHONY : common.i

# target to preprocess a source file
common.cpp.i:
	$(MAKE) -f CMakeFiles/unittest.dir/build.make CMakeFiles/unittest.dir/common.cpp.i
.PHONY : common.cpp.i

common.s: common.cpp.s

.PHONY : common.s

# target to generate assembly for a file
common.cpp.s:
	$(MAKE) -f CMakeFiles/unittest.dir/build.make CMakeFiles/unittest.dir/common.cpp.s
.PHONY : common.cpp.s

home/sdnv/PinkRabbitMQ/src/AddInNative.o: home/sdnv/PinkRabbitMQ/src/AddInNative.cpp.o

.PHONY : home/sdnv/PinkRabbitMQ/src/AddInNative.o

# target to build an object file
home/sdnv/PinkRabbitMQ/src/AddInNative.cpp.o:
	$(MAKE) -f CMakeFiles/PinkRabbitMQ64.dir/build.make CMakeFiles/PinkRabbitMQ64.dir/home/sdnv/PinkRabbitMQ/src/AddInNative.cpp.o
.PHONY : home/sdnv/PinkRabbitMQ/src/AddInNative.cpp.o

home/sdnv/PinkRabbitMQ/src/AddInNative.i: home/sdnv/PinkRabbitMQ/src/AddInNative.cpp.i

.PHONY : home/sdnv/PinkRabbitMQ/src/AddInNative.i

# target to preprocess a source file
home/sdnv/PinkRabbitMQ/src/AddInNative.cpp.i:
	$(MAKE) -f CMakeFiles/PinkRabbitMQ64.dir/build.make CMakeFiles/PinkRabbitMQ64.dir/home/sdnv/PinkRabbitMQ/src/AddInNative.cpp.i
.PHONY : home/sdnv/PinkRabbitMQ/src/AddInNative.cpp.i

home/sdnv/PinkRabbitMQ/src/AddInNative.s: home/sdnv/PinkRabbitMQ/src/AddInNative.cpp.s

.PHONY : home/sdnv/PinkRabbitMQ/src/AddInNative.s

# target to generate assembly for a file
home/sdnv/PinkRabbitMQ/src/AddInNative.cpp.s:
	$(MAKE) -f CMakeFiles/PinkRabbitMQ64.dir/build.make CMakeFiles/PinkRabbitMQ64.dir/home/sdnv/PinkRabbitMQ/src/AddInNative.cpp.s
.PHONY : home/sdnv/PinkRabbitMQ/src/AddInNative.cpp.s

home/sdnv/PinkRabbitMQ/src/Connection.o: home/sdnv/PinkRabbitMQ/src/Connection.cpp.o

.PHONY : home/sdnv/PinkRabbitMQ/src/Connection.o

# target to build an object file
home/sdnv/PinkRabbitMQ/src/Connection.cpp.o:
	$(MAKE) -f CMakeFiles/PinkRabbitMQ64.dir/build.make CMakeFiles/PinkRabbitMQ64.dir/home/sdnv/PinkRabbitMQ/src/Connection.cpp.o
.PHONY : home/sdnv/PinkRabbitMQ/src/Connection.cpp.o

home/sdnv/PinkRabbitMQ/src/Connection.i: home/sdnv/PinkRabbitMQ/src/Connection.cpp.i

.PHONY : home/sdnv/PinkRabbitMQ/src/Connection.i

# target to preprocess a source file
home/sdnv/PinkRabbitMQ/src/Connection.cpp.i:
	$(MAKE) -f CMakeFiles/PinkRabbitMQ64.dir/build.make CMakeFiles/PinkRabbitMQ64.dir/home/sdnv/PinkRabbitMQ/src/Connection.cpp.i
.PHONY : home/sdnv/PinkRabbitMQ/src/Connection.cpp.i

home/sdnv/PinkRabbitMQ/src/Connection.s: home/sdnv/PinkRabbitMQ/src/Connection.cpp.s

.PHONY : home/sdnv/PinkRabbitMQ/src/Connection.s

# target to generate assembly for a file
home/sdnv/PinkRabbitMQ/src/Connection.cpp.s:
	$(MAKE) -f CMakeFiles/PinkRabbitMQ64.dir/build.make CMakeFiles/PinkRabbitMQ64.dir/home/sdnv/PinkRabbitMQ/src/Connection.cpp.s
.PHONY : home/sdnv/PinkRabbitMQ/src/Connection.cpp.s

home/sdnv/PinkRabbitMQ/src/RabbitMQClient.o: home/sdnv/PinkRabbitMQ/src/RabbitMQClient.cpp.o

.PHONY : home/sdnv/PinkRabbitMQ/src/RabbitMQClient.o

# target to build an object file
home/sdnv/PinkRabbitMQ/src/RabbitMQClient.cpp.o:
	$(MAKE) -f CMakeFiles/PinkRabbitMQ64.dir/build.make CMakeFiles/PinkRabbitMQ64.dir/home/sdnv/PinkRabbitMQ/src/RabbitMQClient.cpp.o
.PHONY : home/sdnv/PinkRabbitMQ/src/RabbitMQClient.cpp.o

home/sdnv/PinkRabbitMQ/src/RabbitMQClient.i: home/sdnv/PinkRabbitMQ/src/RabbitMQClient.cpp.i

.PHONY : home/sdnv/PinkRabbitMQ/src/RabbitMQClient.i

# target to preprocess a source file
home/sdnv/PinkRabbitMQ/src/RabbitMQClient.cpp.i:
	$(MAKE) -f CMakeFiles/PinkRabbitMQ64.dir/build.make CMakeFiles/PinkRabbitMQ64.dir/home/sdnv/PinkRabbitMQ/src/RabbitMQClient.cpp.i
.PHONY : home/sdnv/PinkRabbitMQ/src/RabbitMQClient.cpp.i

home/sdnv/PinkRabbitMQ/src/RabbitMQClient.s: home/sdnv/PinkRabbitMQ/src/RabbitMQClient.cpp.s

.PHONY : home/sdnv/PinkRabbitMQ/src/RabbitMQClient.s

# target to generate assembly for a file
home/sdnv/PinkRabbitMQ/src/RabbitMQClient.cpp.s:
	$(MAKE) -f CMakeFiles/PinkRabbitMQ64.dir/build.make CMakeFiles/PinkRabbitMQ64.dir/home/sdnv/PinkRabbitMQ/src/RabbitMQClient.cpp.s
.PHONY : home/sdnv/PinkRabbitMQ/src/RabbitMQClient.cpp.s

home/sdnv/PinkRabbitMQ/src/RabbitMQClientNative.o: home/sdnv/PinkRabbitMQ/src/RabbitMQClientNative.cpp.o

.PHONY : home/sdnv/PinkRabbitMQ/src/RabbitMQClientNative.o

# target to build an object file
home/sdnv/PinkRabbitMQ/src/RabbitMQClientNative.cpp.o:
	$(MAKE) -f CMakeFiles/PinkRabbitMQ64.dir/build.make CMakeFiles/PinkRabbitMQ64.dir/home/sdnv/PinkRabbitMQ/src/RabbitMQClientNative.cpp.o
.PHONY : home/sdnv/PinkRabbitMQ/src/RabbitMQClientNative.cpp.o

home/sdnv/PinkRabbitMQ/src/RabbitMQClientNative.i: home/sdnv/PinkRabbitMQ/src/RabbitMQClientNative.cpp.i

.PHONY : home/sdnv/PinkRabbitMQ/src/RabbitMQClientNative.i

# target to preprocess a source file
home/sdnv/PinkRabbitMQ/src/RabbitMQClientNative.cpp.i:
	$(MAKE) -f CMakeFiles/PinkRabbitMQ64.dir/build.make CMakeFiles/PinkRabbitMQ64.dir/home/sdnv/PinkRabbitMQ/src/RabbitMQClientNative.cpp.i
.PHONY : home/sdnv/PinkRabbitMQ/src/RabbitMQClientNative.cpp.i

home/sdnv/PinkRabbitMQ/src/RabbitMQClientNative.s: home/sdnv/PinkRabbitMQ/src/RabbitMQClientNative.cpp.s

.PHONY : home/sdnv/PinkRabbitMQ/src/RabbitMQClientNative.s

# target to generate assembly for a file
home/sdnv/PinkRabbitMQ/src/RabbitMQClientNative.cpp.s:
	$(MAKE) -f CMakeFiles/PinkRabbitMQ64.dir/build.make CMakeFiles/PinkRabbitMQ64.dir/home/sdnv/PinkRabbitMQ/src/RabbitMQClientNative.cpp.s
.PHONY : home/sdnv/PinkRabbitMQ/src/RabbitMQClientNative.cpp.s

home/sdnv/PinkRabbitMQ/src/linux/ConnectionImpl.o: home/sdnv/PinkRabbitMQ/src/linux/ConnectionImpl.cpp.o

.PHONY : home/sdnv/PinkRabbitMQ/src/linux/ConnectionImpl.o

# target to build an object file
home/sdnv/PinkRabbitMQ/src/linux/ConnectionImpl.cpp.o:
	$(MAKE) -f CMakeFiles/PinkRabbitMQ64.dir/build.make CMakeFiles/PinkRabbitMQ64.dir/home/sdnv/PinkRabbitMQ/src/linux/ConnectionImpl.cpp.o
.PHONY : home/sdnv/PinkRabbitMQ/src/linux/ConnectionImpl.cpp.o

home/sdnv/PinkRabbitMQ/src/linux/ConnectionImpl.i: home/sdnv/PinkRabbitMQ/src/linux/ConnectionImpl.cpp.i

.PHONY : home/sdnv/PinkRabbitMQ/src/linux/ConnectionImpl.i

# target to preprocess a source file
home/sdnv/PinkRabbitMQ/src/linux/ConnectionImpl.cpp.i:
	$(MAKE) -f CMakeFiles/PinkRabbitMQ64.dir/build.make CMakeFiles/PinkRabbitMQ64.dir/home/sdnv/PinkRabbitMQ/src/linux/ConnectionImpl.cpp.i
.PHONY : home/sdnv/PinkRabbitMQ/src/linux/ConnectionImpl.cpp.i

home/sdnv/PinkRabbitMQ/src/linux/ConnectionImpl.s: home/sdnv/PinkRabbitMQ/src/linux/ConnectionImpl.cpp.s

.PHONY : home/sdnv/PinkRabbitMQ/src/linux/ConnectionImpl.s

# target to generate assembly for a file
home/sdnv/PinkRabbitMQ/src/linux/ConnectionImpl.cpp.s:
	$(MAKE) -f CMakeFiles/PinkRabbitMQ64.dir/build.make CMakeFiles/PinkRabbitMQ64.dir/home/sdnv/PinkRabbitMQ/src/linux/ConnectionImpl.cpp.s
.PHONY : home/sdnv/PinkRabbitMQ/src/linux/ConnectionImpl.cpp.s

tests.o: tests.cpp.o

.PHONY : tests.o

# target to build an object file
tests.cpp.o:
	$(MAKE) -f CMakeFiles/unittest.dir/build.make CMakeFiles/unittest.dir/tests.cpp.o
.PHONY : tests.cpp.o

tests.i: tests.cpp.i

.PHONY : tests.i

# target to preprocess a source file
tests.cpp.i:
	$(MAKE) -f CMakeFiles/unittest.dir/build.make CMakeFiles/unittest.dir/tests.cpp.i
.PHONY : tests.cpp.i

tests.s: tests.cpp.s

.PHONY : tests.s

# target to generate assembly for a file
tests.cpp.s:
	$(MAKE) -f CMakeFiles/unittest.dir/build.make CMakeFiles/unittest.dir/tests.cpp.s
.PHONY : tests.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... test"
	@echo "... PinkRabbitMQ64"
	@echo "... unittest"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... common.o"
	@echo "... common.i"
	@echo "... common.s"
	@echo "... home/sdnv/PinkRabbitMQ/src/AddInNative.o"
	@echo "... home/sdnv/PinkRabbitMQ/src/AddInNative.i"
	@echo "... home/sdnv/PinkRabbitMQ/src/AddInNative.s"
	@echo "... home/sdnv/PinkRabbitMQ/src/Connection.o"
	@echo "... home/sdnv/PinkRabbitMQ/src/Connection.i"
	@echo "... home/sdnv/PinkRabbitMQ/src/Connection.s"
	@echo "... home/sdnv/PinkRabbitMQ/src/RabbitMQClient.o"
	@echo "... home/sdnv/PinkRabbitMQ/src/RabbitMQClient.i"
	@echo "... home/sdnv/PinkRabbitMQ/src/RabbitMQClient.s"
	@echo "... home/sdnv/PinkRabbitMQ/src/RabbitMQClientNative.o"
	@echo "... home/sdnv/PinkRabbitMQ/src/RabbitMQClientNative.i"
	@echo "... home/sdnv/PinkRabbitMQ/src/RabbitMQClientNative.s"
	@echo "... home/sdnv/PinkRabbitMQ/src/linux/ConnectionImpl.o"
	@echo "... home/sdnv/PinkRabbitMQ/src/linux/ConnectionImpl.i"
	@echo "... home/sdnv/PinkRabbitMQ/src/linux/ConnectionImpl.s"
	@echo "... tests.o"
	@echo "... tests.i"
	@echo "... tests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

